### ISSUE TITLE
Llama 2 on v4-32

### ISSUE THREAD

**Issue by versae** [lucaslingle/mu_transformer#15]
Hi! Congrats on the project, very clean and nice!

I was wondering if there are any plans to include common configurations like Llama 2 models and Mistral, or how complicated would that be. I'm looking into training smaller Llama 2 models on a v4-32 and would like to test this library.

Cheers.

**Comment by lucaslingle** [comment]
Hi, thanks for your interest!

I haven't tried loading checkpoints from pretrained models such as Llama-2, because the codebase was mainly made for studying transformers with mu-parameterization, which affects initialization and thus requires training from scratch. 

If you're just interested in the architecture modifications used by Llama-2, the codebase currently focuses on MHA and ReLU/Squared ReLU only, but I think it should be straightforward to add appropriate support for e.g., GQA and SwiGLU. 
When I get some free time, I can add support in a new branch if you'd like.
